*--------------------------------------------------------------------------------------*		
|                          REGRAS DO JOGO!										              
| 1) O jogo é 1x3, ou seja, um jogador contra 3 bots inteligentes;							
| 2) São distribuidas 7 cartas aleatórias para cada jogador;									
| 3) Cada jogador só pode jogar 1 carta por vez;												
| 4) Caso o jogador não tenha uma carta válida para a jogada, uma nova carta 				
| será automaticamente puxada do deck e jogada, caso seja válida;                     		
| 5) O jogo acaba quando não houver mais cartas no deck ou quando algum jogador zerar		
| o número de cartas na mão;																	
| 6) Se não houver mais cartas no deck, ganha o jogador que tiver menos cartas! 				
|																									
|     		  ---  Aperte qualquer tecla para voltar ---											
|																									
*--------------------------------------------------------------------------------------*